version: '3.1'
services:    
    flask-serv:
        build: .
        restart: always
        image: flask-server
        ports:
            - 8080:8080
        volumes:  # when pushing to server, remove the first dot here in front of /mnt
            - /mnt/ssd/ds_ftp/classla_OS2022:/usr/src/app/classla_OS2022
            - /swagger_server/classla/classla_resources:/root/classla_resources
