version: '3.1'
services:
  flask-serv:
    build: .
    restart: always
    image: flask-server
    ports:
      - "8080:8080"
    volumes: # when pushing to server, remove the first dot here in front of /mnt
      - /mnt/ssd/ds_ftp/classla_OS2022:/usr/src/app/classla_OS2022
      - ../classla/classla_resources:/root/classla_resources
    environment:
      - PYTHONUNBUFFERED=1
      - MDB_DATABASE=corpus_120k
      - MDB_HOST=164.8.252.72
      - MDB_PORT=3306
      - MDB_USER=rsdo5
      - MDB_PASSWORD=rsdo5mysql
  tika2:
    image: apache/tika:1.28.4-full
    entrypoint: [ "/bin/sh", "-c", "java -jar /tika-server-1.28.4.jar -h 0.0.0.0 -p 9999" ]
    restart: always
    ports:
      - "9999:9999"
  ate-api:
    build: ./ATEapi
    restart: always
 #   ports:
    #  - "5000:5000"
    volumes:
      - ../classla/classla_resources:/home/appuser/classla_resources