# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IzlusciAsyncBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, conllus: List[str]=None, prepovedane_besede: List[str]=None, definicje: bool=False):  # noqa: E501
        """IzlusciAsyncBody - a model defined in Swagger

        :param conllus: The conllus of this IzlusciAsyncBody.  # noqa: E501
        :type conllus: List[str]
        :param prepovedane_besede: The prepovedane_besede of this IzlusciAsyncBody.  # noqa: E501
        :type prepovedane_besede: List[str]
        """
        self.swagger_types = {
            'conllus': List[str],
            'prepovedane_besede': List[str],
            'definicije':bool
        }

        self.attribute_map = {
            'conllus': 'conllus',
            'prepovedane_besede': 'prepovedaneBesede',
            'definicije':'definicije'
        }
        self._conllus = conllus
        self._prepovedane_besede = prepovedane_besede
        self._definicije=definicje

    @classmethod
    def from_dict(cls, dikt) -> 'IzlusciAsyncBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The izlusciAsync_body of this IzlusciAsyncBody.  # noqa: E501
        :rtype: IzlusciAsyncBody
        """
        return util.deserialize_model(dikt, cls)



    @property
    def definicije(self) -> bool:
        """Gets the conllus of this IzlusciSyncBody.


        :return: The conllus of this IzlusciSyncBody.
        :rtype: List[str]
        """
        return self._definicije

    @definicije.setter
    def definicije(self, definicije: bool):
        """Sets the conllus of this IzlusciSyncBody.


        :param conllus: The conllus of this IzlusciSyncBody.
        :type conllus: List[str]
        """

        self._definicije = definicije


    @property
    def conllus(self) -> List[str]:
        """Gets the conllus of this IzlusciAsyncBody.


        :return: The conllus of this IzlusciAsyncBody.
        :rtype: List[str]
        """
        return self._conllus

    @conllus.setter
    def conllus(self, conllus: List[str]):
        """Sets the conllus of this IzlusciAsyncBody.


        :param conllus: The conllus of this IzlusciAsyncBody.
        :type conllus: List[str]
        """

        self._conllus = conllus

    @property
    def prepovedane_besede(self) -> List[str]:
        """Gets the prepovedane_besede of this IzlusciAsyncBody.


        :return: The prepovedane_besede of this IzlusciAsyncBody.
        :rtype: List[str]
        """
        return self._prepovedane_besede

    @prepovedane_besede.setter
    def prepovedane_besede(self, prepovedane_besede: List[str]):
        """Sets the prepovedane_besede of this IzlusciAsyncBody.


        :param prepovedane_besede: The prepovedane_besede of this IzlusciAsyncBody.
        :type prepovedane_besede: List[str]
        """

        self._prepovedane_besede = prepovedane_besede
