# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IzlusciSyncBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, conllus: List[str]=None, prepovedane_besede: List[str]=None):  # noqa: E501
        """IzlusciSyncBody - a model defined in Swagger

        :param conllus: The conllus of this IzlusciSyncBody.  # noqa: E501
        :type conllus: List[str]
        :param prepovedane_besede: The prepovedane_besede of this IzlusciSyncBody.  # noqa: E501
        :type prepovedane_besede: List[str]
        """
        self.swagger_types = {
            'conllus': List[str],
            'prepovedane_besede': List[str]
        }

        self.attribute_map = {
            'conllus': 'conllus',
            'prepovedane_besede': 'prepovedaneBesede'
        }
        self._conllus = conllus
        self._prepovedane_besede = prepovedane_besede

    @classmethod
    def from_dict(cls, dikt) -> 'IzlusciSyncBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The izlusciSync_body of this IzlusciSyncBody.  # noqa: E501
        :rtype: IzlusciSyncBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conllus(self) -> List[str]:
        """Gets the conllus of this IzlusciSyncBody.


        :return: The conllus of this IzlusciSyncBody.
        :rtype: List[str]
        """
        return self._conllus

    @conllus.setter
    def conllus(self, conllus: List[str]):
        """Sets the conllus of this IzlusciSyncBody.


        :param conllus: The conllus of this IzlusciSyncBody.
        :type conllus: List[str]
        """

        self._conllus = conllus

    @property
    def prepovedane_besede(self) -> List[str]:
        """Gets the prepovedane_besede of this IzlusciSyncBody.


        :return: The prepovedane_besede of this IzlusciSyncBody.
        :rtype: List[str]
        """
        return self._prepovedane_besede

    @prepovedane_besede.setter
    def prepovedane_besede(self, prepovedane_besede: List[str]):
        """Sets the prepovedane_besede of this IzlusciSyncBody.


        :param prepovedane_besede: The prepovedane_besede of this IzlusciSyncBody.
        :type prepovedane_besede: List[str]
        """

        self._prepovedane_besede = prepovedane_besede
