# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OznaciBesediloAsyncBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, besedilo: str=None):  # noqa: E501
        """OznaciBesediloAsyncBody - a model defined in Swagger

        :param besedilo: The besedilo of this OznaciBesediloAsyncBody.  # noqa: E501
        :type besedilo: str
        """
        self.swagger_types = {
            'besedilo': str
        }

        self.attribute_map = {
            'besedilo': 'besedilo'
        }
        self._besedilo = besedilo

    @classmethod
    def from_dict(cls, dikt) -> 'OznaciBesediloAsyncBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The oznaciBesediloAsync_body of this OznaciBesediloAsyncBody.  # noqa: E501
        :rtype: OznaciBesediloAsyncBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def besedilo(self) -> str:
        """Gets the besedilo of this OznaciBesediloAsyncBody.


        :return: The besedilo of this OznaciBesediloAsyncBody.
        :rtype: str
        """
        return self._besedilo

    @besedilo.setter
    def besedilo(self, besedilo: str):
        """Sets the besedilo of this OznaciBesediloAsyncBody.


        :param besedilo: The besedilo of this OznaciBesediloAsyncBody.
        :type besedilo: str
        """

        self._besedilo = besedilo
